server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: inventory
          uri: http://localhost:8082
          predicates:
            - Path=/inventories/**, 
        - id: dashboard
          uri: http://localhost:8083
          predicates:
            - Path=, 
        - id: order
          uri: http://localhost:8084
          predicates:
            - Path=/orders/**, 
        - id: delivery
          uri: http://localhost:8085
          predicates:
            - Path=/deliveries/**, 
        - id: cancelled event
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: deadline
          uri: http://localhost:8087
          predicates:
            - Path=/deadlines/**, /undefined/**, /undefined/**, /undefined/**, /undefined/**, /undefined/**, 
        - id: payment
          uri: http://localhost:0
          predicates:
            - Path=/payments/**, 
        - id: account
          uri: http://localhost:0
          predicates:
            - Path=/accounts/**, /undefined/**, /undefined/**, /undefined/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: inventory
          uri: http://inventory:8080
          predicates:
            - Path=/inventories/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**, 
        - id: cancelled event
          uri: http://cancelledEvent:8080
          predicates:
            - Path=, 
        - id: deadline
          uri: http://deadline:8080
          predicates:
            - Path=/deadlines/**, /undefined/**, /undefined/**, /undefined/**, /undefined/**, /undefined/**, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: account
          uri: http://account:8080
          predicates:
            - Path=/accounts/**, /undefined/**, /undefined/**, /undefined/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
